language: python
python:
  - "2.7"
  - "3.2"
install:
  - pip install coveralls
  - pip install pep8
script:
  - pep8 hypergraph
  - coverage run --source=hypergraph setup.py test
after_success:
    coveralls
